### ISSUE TITLE
Any interest  in building a chinese Lisp forum

### ISSUE THREAD

**Issue by oneforalone** [Lisp-Life/Lisp-China#2]
Just as the title said, since i started translating & learning Lisp, i always want to build a forum for Chinese lispers, but i don't find any partner, would you like to join me? I've saw some nice forums (https://scientistdao.org/) but i don't have much time to do the research. I believe we could build one for some chinese that want to learn Lisp but have some difficult in reading the origin docs. Please contact me via wechat:  qiduo-duan.
Thanks.
Yuqi

**Comment by alaskasquirrel** [comment]
[Emacs China](https://emacs-china.org/) is probably the best lisper community to use to promote Lisp.

I’m not a computer science graduate, and realized the importance of reading English documentation during my self-learning, relying on Chinese translations is not very feasible.

Vincent writed [Lisp journey](https://lisp-journey.gitlab.io/), his hidden plan is to make Common Lisp popular again.

I see, Scheme and Common Lisp are far away from software engineering environment and are unlikely to develop.

**Comment by oneforalone** [comment]
Okay, I got you. Anyway, happy lisping.
